version: '3'

services:

  mysql:
    image: mysql:5.6.41
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
    - default
    expose:
    - "3306"
    ports:
    - "3306:3306"

  wayne-backend:
    image: <>/kube-web-backend:latest
    command: /opt/kube-web/backend
    environment:
      GOPATH: "/go"
    volumes:
    - ./conf/app.conf:/opt/kube-web/conf/app.conf
    depends_on:
    - mysql
    restart: always
    networks:
    - default
    ports:
    - "8080:8080"
